#+BEGIN_HTML
---
layout: post
title: 炸弹人攻略
excerpt:
keywords: ""
categories:
tags: []
---
#+END_HTML

* 老炸弹人的觉悟
   被举报次数常年稳定在10~15次，最多时上过20次，可惜没有截图。


* 技能分析

** 感应地雷
    埋布隐形的地雷，不会被真实视域检测到，但是有敌方单位在地雷的400生效范围内会显形。敌人在生效范围内停留超过1.6秒会使地雷爆炸。爆炸在爆炸范围内造成全额伤害，对建筑物造成25%伤害。起重港的噩梦！

*** 技能数据
    - 伤害：200 400 600 800
    - 作用范围：400
    - 启动延迟：1.75
    - 对建筑伤害：25%
    - 技能：点目标
    - 伤害类型：魔法
    - 无视技能免疫：是
    - 耗魔：110 130 150 170
    - 技能冷却：12

*** tips
     感应地雷的生效范围内不能再放置地雷。
     感应地雷不会阻止中立生物产生。
     地雷持续时间没有上限，除非爆炸或被摧毁。
     隐形单位也能触发地雷。
     飞行单位不会触发地雷。
     敌方英雄将地雷摧毁可以获得30金钱。

*** 技能分析
     简称小雷，炸弹人的前中期核心技能，用于伤害和打钱。伤害成长十分优秀，满级800的范围伤害在dota2中首屈一指，甚至高于火女和莱恩的二级大招，是任何脆皮法师、敏核的噩梦。在符点与敌方野区布下地雷，即使没有击杀，也能有效干扰对方打钱速度。地雷到达3级可以直接清掉一波兵，因此炸弹人的打钱效率相当高。
     炸弹人的输出量与埋雷的数量几乎成正比，因此不要太纠结于埋雷地点，只要蓝量充足，CD一好就近埋一颗总不会有错。地雷耗蓝很高，必须有充足的回蓝装备提供支持。感应地雷技能升级后，之前埋的地雷伤害也会提升，所以对线期等级低时多埋一些雷，可以节省一些蓝量。推荐主升。


** 静滞陷阱
    埋设一个隐形的陷阱，当有敌方单位靠近时会马上自动触发，造成缠绕。猎手镇的灾难！

*** 技能数据
    - 缠绕作用范围：600
    - 触发陷阱范围：400
    - 陷阱渐隐时间：2.0
    - 缠绕持续时间：2 3 4 5
    - 技能：点目标
    - 无视技能免疫：否
    - 耗魔：80 110 140 160
    - 技能冷却：20.0 16.0 13.0 10.0

*** tips
     静滞陷阱触发后将摧毁作用范围内的其他静滞陷阱。
     隐形单位不会触发静滞陷阱。
     静滞陷阱不能阻止中立生物产生。

*** 技能分析
     简称晕雷，炸弹人最容易被忽视的强力技能。因为小雷的爆炸延迟为1.6s，小雷晕雷重合放置后，一级2s的缠绕时间能够使小雷能够稳定炸到人。在团战中，满级5s的缠绕时间，甚至比大树的满级大招都要久，可以为队友创造出良好的输出环境。
     耗蓝同样很高，并且控制不稳定，不推荐主升，但前期一定要点一级来配合小雷稳定输出。建议4级时点一级用于稳定踩雷，后期再看情况补满。


** 爆破起飞！
    工程师冲到敌人中间，在相遇时引爆炸药，造成大量范围伤害，并沉默敌人。引爆时会对工程师造成最大生命值50%的伤害。我们是要去哪？

*** 技能数据
    - 全额伤害：300 400 500 600
    - 沉默持续时间：4 5 6 7
    - 作用范围：400
    - 对自身的最大生命值伤害：50%
    - 技能：点目标
    - 伤害类型：魔法
    - 无视技能免疫：否
    - 耗魔：100 125 150 175
    - 技能冷却：35

*** tips
     若使用本技能后死亡将视为自杀，敌方英雄将不会获得金钱和经验。
     即使自杀，工程师依然能获得杀死的敌方英雄对应的经验值。
     自杀攻击将摧毁树木。

*** 技能分析
     简称自爆，是炸弹人集爆发，沉默，自保，回复于一体的神级技能。一级就有300点的可观爆发，使得炸弹人在前期有着很强的线上对拼能力，在游走gank时也能起到不错的的作用。在对线期时自爆，由于是自杀，对方将不会得到金钱与经验，炸弹人只会损失一些金钱，却可以满血满蓝tp回线上，相当于50元的tp加掉的一点钱换了一个奶酪。相比运吃喝补给的高昂费用，和走回家的时间浪费，自爆无疑是酱油的福音。
     自爆虽然伤害高，沉默时间长，但有着1s的施法前摇和1s的滞空时间，自损一半血量，并且会被各种控制技能打断，因此使用难度很高。能不能放出好的自爆，决定了炸弹人对线期的优劣。建议副升。

     炸弹人的自爆基本有3种使用方法。
     对线期线上对拼时，可以先用平A和小雷消耗对方，自己抗一些伤害。等对方控制技能交完，自己在半血以下时原地自爆，即使无法击杀也能给对面造成巨大消耗。
     在打团或gank中，敌方是蚂蚁，女王这类有逃生技能的英雄，或队友没有稳定先手控时，自爆适合打先手。一般要躲在敌方视野盲区，比如树林和高台，预判敌人2s后的走位自爆上去，让队友跟进追杀，自己看情况追人或逃跑。
     队友有稳定的先手控时，自爆一般要后手使用以保证成功率，队友控住敌人直接爆上去即可。

*** 注意事项
     绝大部分控制技能都能打断自爆，因此自爆的时机与位置一定要把握好，尽量卡视野使用。
     不要贪图埋雷而将蓝用光，导致没有蓝自爆，也要注意敌方消蓝英雄，以防万一可以带个芒果应急。
     别忘了死前将钱用光，剩的零钱全部用来买小蓝和真假眼。


** 遥控炸弹
    埋设一颗隐形的炸弹，只有在你的控制下经过简短的延迟才会引爆。爆炸对建筑无效。 可用神杖升级。矿工湾的陷落！

*** 技能数据
    - 伤害：300 450 600
    - 爆炸范围：425
    - 施法距离：500
    - 神杖升级伤害：450 600 750
    - 炸弹持续时间：600.0
    - 启动延迟时间：2.0
    - 神杖升级施法距离：700
    - 技能：点目标
    - 伤害类型：魔法
    - 无视技能免疫：否
    - 可用阿哈利姆神杖升级技能威力。 
    - 提高伤害和施法距离。 
    - 耗魔：200 240 300
    - 技能冷却：10.0 10.0 10.0

*** tips
     敌方英雄摧毁炸弹将获得10金钱。

*** 技能分析
     简称大雷，炸弹人的后期核心技能。如果说小雷是无差别杀伤，那么大雷就是定向爆破。可堆叠，可遥控的特性使得大雷的爆发能力更强，在后期更容易完成击杀。伤害虽然没有小雷那么优秀，但出A杖后也拥有满级750点魔法伤害，叠加后伤害量非常可观，只需5颗就能秒杀大部分英雄。一般会在高地塔前，兵线上，树林中，肉山点这些地方大量埋设。
     大雷也是后期炸弹人的团战输出来源。10秒cd，750点的AOE伤害能为队伍补足一些输出。而出了A杖以太之后900码的施法距离，配合425的爆炸范围，更能让炸弹人在1325码外安全输出。
     但前期大雷这个技能性价比太低，200耗蓝300的伤害，对比小雷+晕雷170+80耗蓝800伤害，差距明显。蓝量本来就很缺的炸弹人是埋不出几个大雷的。建议前期不学，到12级左右再点高。


** 集中引爆
    直接引爆目标区域内所有遥控炸弹。既然能点燃所有引线那干嘛只点一根？

*** 技能数据
    - 作用范围：700
    - 技能：点目标
    - 伤害类型：魔法
    - 耗魔：0
    - 技能冷却：1.0 1.0 1.0

*** 技能分析
    集中引爆技能能够方便地引爆你的地雷，不至于在敌人经过地雷时还要框选地雷引爆，错过最佳的引爆时机。但一定要注意，别把不该爆的地雷也爆掉了。


** 雷区标识
    在指定地点放置警示牌，提醒敌人前方有雷。一次只能出现一个标识，放下新的标识后旧标识将消失。持续180秒。 可用神杖升级。别四处乱跑！

*** 技能数据
    - 标识持续时间：180
    - 技能：点目标
    - 伤害类型：None
    - 可用阿哈利姆神杖升级技能威力。 
    - 雷区标识可以隐去标识附近的所有感应地雷、静滞陷阱和遥控炸弹，不被真实视域发现。 
    - 耗魔：0
    - 技能冷却：360.0

*** 技能分析
    雷区标识有了A杖加成后，能够让小范围内的地雷无法被排，是炸弹人守高的一大杀器。插下雷区标识，敌方只有硬趟地雷和放弃推进两条路可走，不管哪种都会对对方造成惨痛打击。即使没出到A杖也可以插下一个，威慑效果显著。
    技能cd非常长，有360s，也就是雷区标识有180s的真空期。要提防对面趁虚而入。
    建议插在高地塔前，其他位置的插法容错率低，一般不推荐。


* 装备选择


** 灵魂之戒
价格低廉，提供超高额的魔法回复，还能够帮助炸弹人控制自身血量便于自杀。扣除的生命值也是炸弹人不需要的，只要对面没有宙斯、血魔这种英雄，魂戒有cd就磕，追求蓝量的最大化。第一件必出的装备。

推荐指数：★★★★★


** 净化药水
小蓝是性价比很高的道具，持续提供魔法回复。过了对线期要一直贴着小蓝，否则难以支撑炸弹人的巨额魔耗。

推荐指数：★★★★☆


** 魔法芒果
芒果的性价比没有小蓝那么高，但可以在空蓝时磕一个自爆。

推荐指数：★★☆☆☆


** 淬毒之珠
当前版本的毒球没有之前那么强势，效果较差，因此不推荐。如果以后的版本有加强可以考虑出毒球线上点人。

推荐指数：★★☆☆☆


** 侦查守卫\岗哨守卫
作为4、5号位，买一些真假眼是炸弹人的职责。在埋雷阵前最好插个真眼，要是在敌人的眼下埋雷可就尴尬了。

推荐指数：★★★★☆


** 奥术鞋
提供团队魔法回复，也撑一些蓝上限。由于炸弹人急缺魔法，秘法鞋是鞋类的首选。中后期可以拆了合成以太、玲珑心、飞鞋。

推荐指数：★★★★☆


** 静谧之鞋
提供高额的移速和生命回复。在对面有宙斯、风行、卡尔等英雄，远程AOE较多时，绿鞋的生命回复能够保证炸弹人的生存。但绿鞋的回血、加移速都不是炸弹人最需要的，而且生命回复使得自己更难控血控到半血以下，因此优先度没有秘法鞋那么高。

推荐指数：★★★☆☆


** 原力法杖
能够逃生，能够救队友，更能把对面排雷的英雄推到雷上教做人。

推荐指数：★★★★★


** 以太之镜
增加所有技能的施法距离，撑一些回蓝与蓝上限。在优势局可以出一个，方便在推进、打团时扔雷。

推荐指数：★★★★☆


** Eul的神圣法杖
提供高额魔法回复，也能配合自爆来打先手。

推荐指数：★★★★☆


** 微光披风
能救自己，也能救队友。对面法系爆发较高时出。

推荐指数：★★★☆☆


** 幽魂权杖
让对面的物理大哥拿你没办法。对面物理输出较高时出。

推荐指数：★★★☆☆


** 阿哈利姆神杖
炸弹人的后期核心装备。150点的伤害加成有效提升了炸弹人的输出，200码的施法距离加成让炸弹人能在守塔、团战时安全地扔雷。雷区标识的隐形效果更是守高的一大杀器。第四件必出。

推荐指数：★★★★★


** 玲珑心
虽然浪费了玲珑心的法术吸血效果，但25%cd减少能够提升炸弹人30%左右的输出。大后期的质变装备。

推荐指数：★★★★☆


** 血精石
提供高额的魔法回复。但价格比较昂贵，且没有A杖、玲珑心那么质变。

推荐指数：★★★☆☆


** 邪恶镰刀
法师的后期神装。队伍需要你补足控制时出一把。

推荐指数：★★★☆☆


** 远行鞋
飞鞋增加高额移速，也让你更快地赶到战场。后期资金充足时可以买一双。

推荐指数：★★★☆☆


** 永恒之盘
生存装备。后期可以打出自爆+永恒之盘的操作保证自己存活。

推荐指数：★★★☆☆


** 死灵书
用来推塔和反眼，提升一些正面能力。

推荐指数：★★☆☆☆


** 刷新球
用来刷新雷区标识，使炸弹人没有真空期。在雷区标识消失，而敌方即将推上高地时买一个应急。

推荐指数：★★☆☆☆


** 林肯法球
对面有强力的指向性技能时，可选择帮大哥出个林肯挡一挡。

推荐指数：★★☆☆☆


** 银月之晶
后期金钱溢出时就给大哥养个银月。

推荐指数：★★☆☆☆


** 纷争面纱
提供很好的属性与伤害加深。但炸弹人更多时间是在千里之外杀敌，因此伤害加深很少能够给到敌人，因此不推荐。

推荐指数：★☆☆☆☆


** 慧光
慧光只能降低炸弹人的蓝耗，而不能增加地雷的伤害，不推荐。

推荐指数：★☆☆☆☆


** 飓风长戟
推推升级为长戟就无法把敌人推向雷阵。不推荐。

推荐指数：☆☆☆☆☆




* 出装范例

** 劣势及均势
   魂戒、秘法鞋、推推棒、A杖、玲珑心、飞鞋

   前期出魂戒秘法保证自身回蓝。中期补出一件功能装保证生存。后期憋出A杖与玲珑心尽可能提升地雷的输出。

** 优势出装
   魂戒、绿鞋、以太之镜、A杖、血精石、羊刀、飞鞋

   由于要参与推进，绿鞋保证打团过后能有充足的生命回复。以太提供良好的埋雷环境。后期补出羊刀扩大优势。

** 总体思路
   装备的选择相当灵活。除了魂戒、A杖两件核心装，其他装备都要根据局势来取舍。对面发条就出推推，对面血魔就出绿鞋总不会错。

   对于新手不推荐走物理路线。


* 技能加点



#+BEGIN_HTML
<!-- more-forword -->
#+END_HTML


#+BEGIN_HTML
<!-- more -->
#+END_HTML
